### ISSUE TITLE
Backups are happening about every 2.5 minutes

### ISSUE THREAD

**Issue by ClaudiusMinimus** [ProjectEssentials/ProjectEssentials-Backup#4]
### Describe the bug
Not sure if this is a bug or if I have done something wrong. Backups are happening about every 2.5 minutes. I'm developing a modpack for 1.15.2 and am testing in a singleplayer world and will be moving to my server very soon. However, according to [convertworld.com](https://www.convertworld.com/en/time/milliseconds.html) the 15000000 ms specified in my config is equal to 4.17 hour, but the backups are happening every 2.5 minutes (see screenshot below)

Here is the contents of my backup.json:

    {
    "backupEnabled": true,
    "firstLaunchDelay": true,
    "backupCreationDelay": 15000000,
    "backupCompressionLevel": 3,
    "backupDirectoryPath": "backup",
    "backupDateFormat": "yyyy-MM-dd_HH.mm.ss",
    "maxBackupFiles": 10,
    "rollingBackupFilesEnabled": true,
    "removeExtraFiles": true
    }

### Expected behavior
I would like the backups to occur every three hours, which would be 10800000 ms

### Screenshots of backups performed
![Selection_019](https://user-images.githubusercontent.com/17887664/80158360-895dec80-8585-11ea-876f-4ec5bdc5ebb0.png)

### Environment information
- Project Essentials Backup-1.15.2-1.0.1
- Project Essentials Core-MOD-1.15.2-1.1.0
- Java 1.8.0_212
- Minecraft / Forge version: 1.15.2 / 31.1.46 
- OS Linux Mint 19.3

### Log files. (latest.log and debug.log file in attachment)
- [latest.log](https://github.com/ProjectEssentials/ProjectEssentials-Backup/files/4525800/latest.log)
- [debug.log](https://github.com/ProjectEssentials/ProjectEssentials-Backup/files/4525799/debug.log)

Thank you and I look forward to hearing from you.
CM

**Comment by MairwunNx** [comment]
@ClaudiusMinimus thanks and welcome =). Oh. This is a serious problem and it confuses me. Is this problem repeating again? The backup configuration must be changed before starting the server \ game.

**Comment by ClaudiusMinimus** [comment]
Thank you for your reply. 
 For some unknown reason, only one backup was made today. I need to do further testing, but this has been going on for a while. I will let you know as soon as I have more information.
Thanks again,
CM

**Comment by ClaudiusMinimus** [comment]
I've been testing with a singleplayer world with only your backup mod. 
I first set the backupCreationDelay to 150000, which made a backup every 2.5 minutes as expected. I then doubled it to 300000 which made backups every 5 minutes. Tomorrow, I will try again with my modpack to see if I can reproduce the issue.

**Comment by ClaudiusMinimus** [comment]
For whatever reason, the backups are working as normal. Thank you for your help.
