### ISSUE TITLE
Project Essentials Backup 1.15.2-1.0.1 not compatible with recommended Forge: 31.2.0

### ISSUE THREAD

**Issue by ClaudiusMinimus** [ProjectEssentials/ProjectEssentials-Backup#5]
I was filing an issue report for another mod and I saw the following on the latest.log file and I thought you would want to see it.

> [02Jun2020 23:00:24.078] [modloading-worker-7/WARN] [com.mairwunnx.projectessentials.core.EssBase/]: 
            **** Forge version may be incompatible with Project Essentials Backup 1.15.2-1.0.1! ****
    - update or downgrade forge version.
    - update or downgrade mod version.
    - or just create issue on github.

And

>[02Jun2020 23:00:26.340] [modloading-worker-1/WARN] [com.mairwunnx.projectessentials.core.EssBase/]: 
            **** Forge version may be incompatible with Project Essentials Core 1.15.2-1.1.0! ****
    - update or downgrade forge version.
    - update or downgrade mod version.
    - or just create issue on github.
- Minecraft Version: 1.15.2
- Operating System: Linux (amd64) version 4.15.0-99-generic
- Java Version: 1.8.0_251, Oracle Corporation
- Forge: 31.2.0
- Mod: project_essentials_backup 1.15.2-1.0.1
- Mod Id: project_essentials_core 1.15.2-1.1.0

[latest.log](https://github.com/ProjectEssentials/ProjectEssentials-Backup/files/4738828/latest.log)

**Comment by MairwunNx** [comment]
Hello, @ClaudiusMinimus!

It's just a warning about compatibility, 1.X really can be incompatible with 31.2.XX, but also can work fine.

You can just simply ignore this warning, if it not causes any bugs.

**Comment by MairwunNx** [comment]
`2.X.X` backup now is compatible with forge `31.>`.
